[package]
name = "networkflow"
version = "0.1.2"
edition = "2024"
description = "A collection of network flow algorithms."
readme = "README.md"
repository = "https://github.com/pvunderink/networkflow"
license = "MIT"
keywords = ["graph", "max-flow", "min-cost", "networkflow"]

[dependencies]
num = { version = "0.4.3" }
try-partialord = { version = "0.1.3" }
